[[servers]]
name = "time"
url = "127.0.0.1:8111/http"
strip_slug = true
use_tls = false
mcp = true

[[servers]]
name = "ssetime"
url = "127.0.0.1:8111/sse"
strip_slug = true
use_tls = false
mcp = true

[[servers]]
name = "timedocker"
url = "172.17.0.1:8880/mcp"
strip_slug = true
use_tls = false
mcp = true

[[servers]]
name = "fast"
url = "127.0.0.1:9080/mcp"
strip_slug = true
use_tls = false
mcp = true
