[[servers]]
name = "time"
url = "127.0.0.1:8111/http"
strip_slug = true
use_tls = false
mcp = true

[[servers]]
name = "timesse"
url = "127.0.0.1:8111/sse"
strip_slug = true
use_tls = false
mcp = true
